version: '3.8'
services:
  prod:
    container_name: event_api_prod
    image: event-api-prod:1.0.0
    build:
      context: .
      dockerfile: 'Dockerfile'
    command: yarn start:prod
    ports:
      - '3000:3000'
    networks:
      - nestjs-network
    volumes:
      - .:/home/app
      - /home/app/node_modules
    restart: unless-stopped

networks:
  nestjs-network:
